### PR TITLE
Fix issue with missing method argument type

### PR DESCRIPTION
**Pull request by lenaorobei**
Fixed issue:
`"Warning: Declaration of CommunityEngineering\JapaneseName\Model\DataObject\Copy::setAttributeValueFromExtensibleDataObject($target, $code, $value) should be compatible with Magento\Framework\DataObject\Copy::setAttributeValueFromExtensibleDataObject(Magento\Framework\Api\ExtensibleDataInterface $target, $code, $value) in /var/www/html/vendor/community-engineering/module-japanese-name/Model/DataObject/Copy.php on line 19"`

### CODE REVIEW

**Comment by smoskaluk** [comment]
@lenaorobei  I got next error after creating Credit Memo for order with 1 item of simple product.

cr_memo_JP


I've used local inviroment - magento branch 2.4-develop from https://github.com/magento/magento2.git repository + this PR branch - installed according manual here, with no 3 part modules enabled. 
I'm working on PHP 7.2.26-1+ubuntu16.04.1+deb.sury.org+1 (cli) + chromium 79

**Comment by HirokazuNishi** [comment]
@smoskaluk Please provide your environment info as same as magento2 repository requests.

**Comment by lenaorobei** [comment]
@smoskaluk could you please check again?
If will fail please provide additional info, like did you change any configuration? What is the currency of the product?

**Comment by smoskaluk** [comment]
@lenaorobei 
I checked again, and issue is still there. 
I didn't any changes in configuration, all setting are by default, currency is JPY.
I do next:
1. Create simple product
2. Place order with it
3. Create Invoice for this order
4. Create Credit Memo 
5. Open 'Credit Memo' tab on my order page in admin 

image

**Comment by lenaorobei** [comment]
Thanks @smoskaluk, I was able to reproduce this bug and fix the issue.
Could you please check again? Please use `2.3-develop`. This extension is not compatible with `2.4` yet, but we will work on it soon.

**Comment by smoskaluk** [comment]
I've checked, it works.

**Pull request merged**
